version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx_container_pypy
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - ./local_static:/static
    depends_on:
      - web
  web:
    build: .
    container_name: web_container_pypy
    command: bash -c "pypy3 manage.py collectstatic --no-input && pypy3 manage.py makemigrations && pypy3 manage.py migrate && gunicorn task_management.wsgi -b 0.0.0.0:8001"
    depends_on:
      - db
    volumes:
      - ./src:/src
      - ./local_static:/static
    expose:
      - "8001"

    environment:
      - DEBUG=0

    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       memory: 50M
    #     reservations:
    #       cpus: '0.25'
    #       memory: 20M




  db:
    image: postgres:latest
    container_name: postgres_container_pypy